# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "ax3005-fvp"
BBFILE_PATTERN_ax3005-fvp = "^${LAYERDIR}/"
LAYERSERIES_COMPAT_ax3005-fvp = "wrynose whinlatter"
